export const mobileAction = {
    MOBILE_LOGIN_INITIATE: 'MOBILE_LOGIN_INITIATE',
    MOBILE_LOGIN_SUCCESS: 'MOBILE_LOGIN_SUCCESS',
    MOBILE_LOGIN_FAILURE: 'MOBILE_LOGIN_FAILURE',

    OTP_LOGIN_INITIATE: 'OTP_LOGIN_INITIATE',
    OTP_LOGIN_SUCCESS: 'OTP_LOGIN_SUCCESS',
    OTP_LOGIN_FAILURE: 'OTP_LOGIN_FAILURE',
}


export const userAction = {
    USER_LOGIN_INITIATE: 'USER_LOGIN_INITIATE',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    USER_STATUS_INITIATE: 'USER_STATUS_INITIATE',
    USER_STATUS_SUCCESS: 'USER_STATUS_SUCCESS',
    USER_STATUS_FAILURE: 'USER_STATUS_FAILURE',

    USER_ACTIVATE_INITIATE: 'USER_ACTIVATE_INITIATE',
    USER_ACTIVATE_SUCCESS: 'USER_ACTIVATE_SUCCESS',
    USER_ACTIVATE_FAILURE: 'USER_ACTIVATE_FAILURE',


    USER_REJECT_INITIATE: 'USER_REJECT_INITIATE',
    USER_REJECT_SUCCESS: 'USER_REJECT_SUCCESS',
    USER_REJECT_FAILURE: 'USER_REJECT_FAILURE',
}

export const panAction = {
    PAN_LOGIN_INITIATE: 'PAN_LOGIN_INITIATE',
    PAN_LOGIN_SUCCESS: 'PAN_LOGIN_SUCCESS',
    PAN_LOGIN_FAILURE: 'PAN_LOGIN_FAILURE',
}

export const kycAction = {
    KYC_LOGIN_INITIATE: 'KYC_LOGIN_INITIATE',
    KYC_LOGIN_SUCCESS: 'KYC_LOGIN_SUCCESS',
    KYC_LOGIN_FAILURE: 'KYC_LOGIN_FAILURE',
}

export const formAction = {
    FORM_LOGIN_INITIATE: 'FORM_LOGIN_INITIATE',
    FORM_LOGIN_SUCCESS: 'FORM_LOGIN_SUCCESS',
    FORM_LOGIN_FAIILURE: 'FORM_LOGIN_FAILURE',

}


export const adminAction = {

    ADMIN_LOGIN_INITIATE: 'ADMIN_LOGIN_INITIATE',
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAILURE: 'ADMIN_LOGIN_FAILURE',

}

export const ListAction = {  // Admin Dashboard//
    LIST_LOGIN_INITIATE: 'LIST_LOGIN_INITIATE',
    LIST_LOGIN_SUCCESS: 'LIST_LOGIN_SUCCESS',
    LIST_LOGIN_FAILURE: 'LIST_LOGIN_FAILURE',
}

export const verifyAdminAction = {
    VERIFY_LOGIN_INITIATE: 'VERIFY_LOGIN_INITIATE',
    VERIFY_LOGIN_SUCCESS: 'VERIFY_LOGIN_SUCCESS',
    VERIFY_LOGIN_FAILURE: 'VERIFY_LOGIN_FAILURE',


}


export const imageAction = {
    IMAGE_LOGIN_INITIATE: 'IMAGE_LOGIN_INITIATE',
    IMAGE_LOGIN_SUCCESS: 'IMAGE_LOGIN_SUCCESS',
    IMAGE_LOGIN_FAILURE: 'IMAGE_LOGIN_FAILURE',

}

export const adminSlabAction = {
    FETCHING_SLAB_LIST: 'FETCHING_SLAB_LIST',
    SET_SLAB_LIST: 'SET_SLAB_LIST',
    CREATING_SLAB: 'CREATING_SLAB',
    EDITING_SLAB: 'EDITING_SLAB'
}

// export const requestMoneyAction={
//     FETCHING_REQUEST_LIST:'FETCHING_REQUEST_LIST',
//     SET_REQUEST_LIST:'SET_REQUEST_LIST',
// }

export const requestMoneyAction = {
    REQUEST_LIST_INITIATE: 'REQUEST_LIST_INITIATE',
    REQUEST_LIST_SUCCESS: 'REQUEST_LIST_SUCCESS',
    REQUEST_LIST_FAILURE: 'REQUEST_LIST_FAILURE',

    GENERATE_REFERENCE_INITIATE: 'GENERATE_REFERENCE_INITIATE',
    GENERATE_REFERENCE_SUCCESS: 'GENERATE_REFERENCE_SUCCESS',
    GENERATE_REFERENCE_FAILURE: 'GENERATE_REFERENCE_FAILURE',

    ADD_REQUEST_INITIATE: 'ADD_REQUEST_INITIATE',   //-----------Save-Ftr-api-------------//
    ADD_REQUEST_SUCCESS: 'ADD_REQUEST_SUCCESS',
    ADD_REQUEST_FAILURE: 'ADD_REQUEST_FAILURE',
}

export const fundRequestAction = {
    FTR_NUMBER_INITIATE:'FTR_NUMBER_INITIATE',
    FTR_NUMBER_SUCCESS:'FTR_NUMBER_SUCCESS',
    FTR_NUMBER_FAILURE:'FTR_NUMBER_FAILURE',

    FUND_REQUEST_INITIATE:'FUND_REQUEST_INITIATE',
    FUND_REQUEST_SUCCESS:'FUND_REQUEST_SUCCESS',
    FUND_REQUEST_FAILURE:'FUND_REQUEST_FAILURE',

    FUND_LIST_ADMIN_INITIATE:'FUND_LIST_ADMIN_INITIATE',
    FUND_LIST_ADMIN_SUCCESS: 'FUND_LIST_ADMIN_SUCCESS',
    FUND_LIST_ADMIN_FAILURE: 'FUND_LIST_ADMIN_FAILURE',

    FUND_LIST_INITIATE:'FUND_LIST_INITIATE',
    FUND_LIST_SUCCESS:'FUND_LIST_SUCCESS',
    FUND_LIST_FAILURE:'FUND_LIST_FAILURE',

    //-------------------Fund-request-admin-accept-rejected-button-work-----------------//
    FUND_ACCEPT_INITIATE:'FUND_ACCEPT_INITIATE',
    FUND_ACCEPT_SUCCESS:'FUND_ACCEPT_SUCCESS',
    FUND_ACCEPT_FAILURE:'FUND_ACCEPT_FAILURE',

    FUND_LIST_SECOND_INITIATE:'FUND_LIST_SECOND_INITIATE',
    FUND_LIST_SECOND_SUCCESS: 'FUND_LIST_SECOND_SUCCESS',
    FUND_LIST_SECOND_FAILURE: 'FUND_LIST_SECOND_FAILURE',

    FUND_ACCEPT_SECOND_INITIATE:'FUND_ACCEPT_SECOND_INITIATE',
    FUND_ACCEPT_SECOND_SUCCESS: 'FUND_ACCEPT_SECOND_SUCCESS',
    FUND_ACCEPT_SECOND_FAILURE: 'FUND_ACCEPT_SECOND_FAILURE',
}


export const paymentDepositAction = {
    UTR_NUMBER_INITIATE: 'UTR_NUMBER_INITIATE',
    UTR_NUMBER_SUCCESS: 'UTR_NUMBER_SUCCESS',
    UTR_NUMBER_FAILURE: 'UTR_NUMBER_FAILURE',

    PAYMENT_DEPOSIT_INITIATE: 'PAYMENT_DEPOSIT_INITIATE',
    PAYMENT_DEPOSIT_SUCCESS: 'PAYMENT_DEPOSIT_SUCCESS',
    PAYMENT_DEPOSIT_FAILURE: 'PAYMENT_DEPOSIT_FAILURE',

    PAYMENT_LIST_INITIATE: 'PAYMENT_LIST_INITIATE',
    PAYMENT_LIST_SUCCESS: 'PAYMENT_LIST_SUCCESS',
    PAYMENT_LIST_FAILURE: 'PAYMENT_LIST_FAILURE',
}

// ----block-unblock action----

export const blockunblockAction = {
    BLOCK_NUMBER_INITIATE: "BLOCK_NUMBER_INITIATE",
    BLOCK_NUMBER_SUCCESS: " BLOCK_NUMBER_SUCCESS",
    BLOCK_NUMBER_FAILURE: "BLOCK_NUMBER_FAILURE"

}

export const profileAction = {
    ADHAR_PHOTO_INITIATE: "ADHAR_PHOTO_INITIATE",
    ADHAR_PHOTO_SUCCESS: "ADHAR_PHOTO_SUCCESS",
    ADHAR_PHOTO_FAILURE: "ADHAR_PHOTO_FAILURE",

    PAN_PHOTO_INITIATE: "PAN_PHOTO_INITIATE",
    PAN_PHOTO_SUCCESS: "PAN_PHOTO_SUCCESS",
    PAN_PHOTO_FAILURE: "PAN_PHOTO_FAILURE",

    BANK_PROOF_INITIATE: "BANK_PROOF_INITIATE",
    BANK_PROOF_SUCCESS: "BANK_PROOF_SUCCESS",
    BANK_PROOF_FAILURE: "BANK_PROOF_FAILURE",

    CHANGE_PHOTO_INITIATE: "CHANGE_PHOTO_INITIATE",
    CHANGE_PHOTO_SUCCESS: "CHANGE_PHOTO_SUCCESS",
    CHANGE_PHOTO_FAILURE: "CHANGE_PHOTO_FAILURE",

    SEND_FOR_REVIEW_INITIATE: "SEND_FOR_REVIEW_INITIATE",
    SEND_FOR_REVIEW_SUCCESS: "SEND_FOR_REVIEW_SUCCESS",
    SEND_FOR_REVIEW_FAILURE: "SEND_FOR_REVIEW_FAILURE",
}


export const walletAction = {

    REQUEST_APPROVE_LIST_INITIATE: 'REQUEST_APPROVE_LIST_INITIATE',
    REQUEST_APPROVE_LIST_SUCCESS: 'REQUEST_APPROVE_LIST_SUCCESS',
    REQUEST_APPROVE_LIST_FAILURE: 'REQUEST_APPROVE_LIST_FAILURE',

    REQUEST_ACCEPT_REJECT_INITIATE: 'REQUEST_ACCEPT_REJECT_INITIATE',
    REQUEST_ACCEPT_REJECT_SUCCESS: 'REQUEST_ACCEPT_REJECT_SUCCESS',
    REQUEST_ACCEPT_REJECT_FAILURE: 'REQUEST_ACCEPT_REJECT_FAILURE',
}

export const addFundOtpAction = {
    FUND_OTP_INITIATE: 'FUND_OTP_INITIATE',
    FUND_OTP_SUCCESS: 'FUND_OTP_SUCCESS',
    FUND_OTP_FAILURE: 'FUND_OTP_FAILURE',

    FUND_ADD_LIST_INITIATE: 'FUND_ADD_LIST_INITIATE',
    FUND_ADD_LIST_SUCCESS: 'FUND_ADD_LIST_SUCCESS',
    FUND_ADD_LIST_FAILURE: 'FUND_ADD_LIST_FAILURE',

    ADD_LIST_INITIATE: 'ADD_LIST_INITIATE',
    ADD_LIST_SUCCESS: 'ADD_LIST_SUCCESS',
    ADD_LIST_FAILURE: 'ADD_LIST_FAILURE',

    BANK_LIST_INITIATE: 'BANK_LIST_INITIATE',
    BANK_LIST_SUCCESS: 'BANK_LIST_SUCCESS',
    BANK_LIST_FAILURE: 'BANK_LIST_FAILURE',

    CONFIRM_OTP_INITIATE: 'CONFIRM_OTP_INITIATE',
    CONFIRM_OTP_SUCCESS: 'CONFIRM_OTP_SUCCESS',
    CONFIRM_OTP_FAILURE: 'CONFIRM_OTP_FAILURE',


}


export const ledgerAction = {
    PARTNER_LEDGER_INITIATE: 'PARTNER_LEDGER_INITIATE',
    PARTNER_LEDGER_SUCCESS: 'PARTNER_LEDGER_SUCCESS',
    PARTNER_LEDGER_FAILURE: 'PARTNER_LEDGER_FAILURE',

    WALLET_BALANCE_INITIATE: "WALLET_BALANCE_INITIATE",
    WALLET_BALANCE_SUCCESS: "WALLET_BALANCE_SUCCESS",
    WALLET_BALANCE_FAILURE: "WALLET_BALANCE_FAILURE"
}


// -------move-distributor-------

export const moveDistributorAction = {
    MOVE_DISTRIBUTOR_INITIATE: 'MOVE_DISTRIBUTOR_INITIATE',
    MOVE_DISTRIBUTOR_SUCCESS: 'MOVE_DISTRIBUTOR_SUCCESS',
    MOVE_DISTRIBUTOR_FAILURE: 'MOVE_DISTRIBUTOR_FAILURE',

    SAVE_DISTRIBUTOR_INITIATE: 'SAVE_DISTRIBUTOR_INITIATE',
    SAVE_DISTRIBUTOR_SUCCESS: 'SAVE_DISTRIBUTOR_SUCCESS',
    SAVE_DISTRIBUTOR_FAILURE: 'SAVE_DISTRIBUTOR_FAILURE',

   

}









